### ISSUE TITLE
Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by hahn** [hidrodixtion/Example-Retrofit-Image-Upload#1]
when pick a picture, got error like this. need new permission

 FATAL EXCEPTION: main
Process: id.web.hn.belajaruploadfile, PID: 29075
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=Intent { dat=content://media/external/images/media/64 }} to activity {id.web.hn.belajaruploadfile/id.web.hn.belajaruploadfile.MainActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/64 from pid=29075, uid=10042 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

**Comment by NizarETH** [comment]
add this permission in your manifest 
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE”/>`
and in your code add this 

```
if (checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
        != PackageManager.PERMISSION_GRANTED) {
    // Should we show an explanation?
    if (shouldShowRequestPermissionRationale(
            Manifest.permission.READ_EXTERNAL_STORAGE)) {
        // Explain to the user why we need to read the contacts
    }
    requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},
            MY_PERMISSIONS_REQUEST_READ_EXTERNAL_STORAGE);

    // MY_PERMISSIONS_REQUEST_READ_EXTERNAL_STORAGE is an
    // app-defined int constant that should be quite unique

    return;
}
```

**Comment by hahn** [comment]
yes, i did that. thanks for the example :D

**Comment by rezazarchi** [comment]
your solution for get file path is no longer work on target SDK +24. According to this link:
https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en
